### PR TITLE
Split out config for large files

### PR DESCRIPTION
**Pull request by dcadams**
Corrects an error caused by the wrong stanza used by the wrong script.

### CODE REVIEW

**Comment by dcadams** [comment]
See https://github.com/Stanford-Online/configuration-secure/pull/362

**Review by stvstnfrd — CHANGES_REQUESTED** [review]
@dcadams What was the error and what caused it to start happening?

Can you provide a little background?

**Comment by dcadams** [comment]
The error has been occurring since the beginning of time as far as I can see.

dump_dbs.py ERROR: large_files has bad or missing "use" parameter, skipping

This makes it difficult to notify when another error occurs.

**Comment by stvstnfrd** [comment]
> This makes it difficult to notify when another error occurs.

How are you looking to determine when a legitimate error occurs?

From the looks of the `dump_dbs.py` file, all the "error" does is print out a line to STDERR and then continues along in the loop; it doesn't appear to actually return a non-zero exit status, which is generally how we determine if a command fails.

**Comment by dcadams** [comment]
In jenkins I have a Post Build Task that looks for the word 'Error' and if there's a match returns an exit status of 1. An E-mail notification sends an email for every unstable build.

**Comment by stvstnfrd** [comment]
whoops, commented on the wrong PR..

**Pull request closed without merging**
