### PR TITLE
File for suclass db dumps.

### PR DESCRIPTION
**Pull request by dcadams**
@stvstnfrd this is currently working on jenkins.

### CODE REVIEW

**Comment by stvstnfrd** [comment]
@dcadams Wait, why are we copy/pasting this entire file?

The only significant change I'm seeing is the output directory
and that's already configurable via the config file.

And we shouldn't need to fork the config file path name either, because each Jenkins task should have its own copy of the source code and config.

**Comment by dcadams** [comment]
Per our conversation Friday I thought I was going to get this running on jenkins and you were going to split it out to different machines. I can close this pr if required.

I'm not sure I'm understanding your last sentence; does that relate to after you have done the split?

**Comment by stvstnfrd** [comment]
Oh, I guess we each walked away with a different understanding. Let's chat after planning.

**Comment by stvstnfrd** [comment]
@dcadams Should this be merged?

**Comment by dcadams** [comment]
This task never made it over to the newer jenkins so I'm ok with trashing it.

**Comment by stvstnfrd** [comment]
@dcadams Can we delete this branch too?

**Pull request closed without merging**
